# Generated by Django 2.2.16 on 2023-01-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_auto_20230127_1325"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="pud_date",
            new_name="pub_date",
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
    ]
