# Generated by Django 2.2.16 on 2023-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={
                "verbose_name": "Пользовательская подписка",
                "verbose_name_plural": "Пользовательские подписки",
            },
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="uq_user_author"
            ),
        ),
    ]
